### ISSUE TITLE
What other fields do you have access to besides My List title and thumbs up/down?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [daltonmenezes/netflix-list-exporter#1]
For instance, I'd be interest in knowing the Nextflix title#, rating, release date (or at least year), last date I watched, genre(s), duration, category#(s). For My List, it's order#.

**Comment by daltonmenezes** [comment]
You can check it looking the API calls.

<img src="https://i.imgur.com/LcsRzeF.png"/>
<img src="https://i.imgur.com/lMpEAnk.png" />
<img src="https://i.imgur.com/YFM3HfE.png" />
