### ISSUE TITLE
Undefined for main list button when try to copy a large list

### ISSUE THREAD

**Issue by bg284** [daltonmenezes/netflix-list-exporter#13]
Was unable to copy to clipboard for main "copy button". Up button and down button working fine.

After deleting some movies from My List (such that # items <400) , tried again and it worked well. Seems to be some sort of limit of how many rows can be copied to clipboard.

**Comment by daltonmenezes** [comment]
Thanks for letting me know @bg284 . This is a browser limitation and I think, unfortunately, we cannot do anything about it. For now I'm going to close this issue and add the "wontfix" label to it, if I notice any workaround to solve it, I will open it again and fix it.
