### ISSUE TITLE
Remove trailing whitespace character when exporting My List

### ISSUE THREAD

**Issue by PetrusKiendys** [daltonmenezes/netflix-list-exporter#4]
Is it possible to [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) the entries when exporting My List?
I'm version tracking My List and currently it's placing a trailing space character at the end of each line.

Partial output of `git diff --color-moved=plain --cached`:

![git-diff-output](https://user-images.githubusercontent.com/2377215/86517484-89058b80-be29-11ea-9a1d-7470c8e945e4.png)

Not sure if exporting ThumbsUp and ThumbsDown lists exhibit the same behaviour as they have remained unchanged for me between commits so far, but it's worth investigating them too.

**Comment by PetrusKiendys** [comment]
A "workaround" script has been described in [another issue](https://github.com/daltonmenezes/netflix-list-exporter/issues/5) for anyone that stumbles over this issue and is impatiently waiting.
It only works for those that have access to a Linux GNU environment and can run commands like `cat`, `awk` and `sort`.
But surely this can easily be ported to Python, Ruby, PowerShell or whatever.

**Comment by yuanLeeMidori** [comment]
Hi! I would like to work on this issue. Please let me know if there is another developer who has been working on it. Thank you!
