### ISSUE TITLE
sort My List export output

### ISSUE THREAD

**Issue by PetrusKiendys** [daltonmenezes/netflix-list-exporter#5]
Is it possible to implement sorting of My List output?
If possible, make a settings page for the extension so that we can customize sort behaviour to our own preference.
Sort option examples could include "as-is" or alphabetically.

The primary use case would be for those of us that version track the output,
to avoid having the lines move around between commits.

Of course, those inclined to solve this on our own can easily do it by running (on Linux):
`cat output.txt | sort >> tracked-mylist-file.txt`

But I'm hoping this can be natively supported by the plugin?

**Comment by PetrusKiendys** [comment]
With a DIY approach, for those interested I'm running a script that does the following:
`cat $inputfile | awk NF | awk '{$1=$1};1' | sort > $outputfile`

The full script is:
```
#!/bin/bash

# Sort "My List" alphabetically
inputfile="nle-mylist.out"
outputfile="NetflixMyList.txt"

cat $inputfile | awk NF | awk '{$1=$1};1' | sort > $outputfile

unset inputfile outputfile

echo "File sorted!"

```

`awk NF` removes the blank line at the end of NLE MyList export output.
`awk '{$1=$1};1'` removes trailing whitespaces.
These commands can possibly be concatenated somehow but whatever, it works well as it is.

Please note that this is just a temporary fix on my end, and I hope that this functionality can be supported natively by the script.
Please write here if there's any updates on this issue.

**Comment by yuanLeeMidori** [comment]
Hi, I'm interested in working on this issue. Has there been any developer working on it already? Thank you!

**Comment by PetrusKiendys** [comment]
Thanks @yuanLeeMidori , now I can throw away my bash scripts :)
